In [1]:
# The Salary_Train and Salary_Test datasets contains Information about Salary of different Person.
# The Dataset Description as follows
# age -- age of a person
# workclass    -- A work class is a grouping of work 
# education    -- Education of an individuals    
# maritalstatus -- Marital status of an individulas    
# occupation     -- occupation of an individuals
# relationship -- ralationship of an individual    
# race --  Race of an Individual
# sex --  Gender of an Individual
# capitalgain --  profit received from the sale of an investment    
# capitalloss    -- A decrease in the value of a capital asset
# hoursperweek -- number of hours work per week    
# native -- Native of an individual
# Salary -- salary of an individual
# Prepare following models to predict Salary:
# 1. Logistic Regression
# 2. Naive Bayes
# 3. KNN
# 4. SVM
# 5. Decision Tree
# 6. Random Forest
# 7. Adaboost

# Calculate different evaluation metrics and select best model from them.

# Notes:
# 1. Do Proper EDA.
# 2. Build model without dropping any columns.

# Dataset:
# Salary_train.csv
# Salary_test.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('Salary_Train.csv')
df.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K

In [4]:
df1 = pd.read_csv('Salary_Test.csv')
df1.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  str
 2   education      30161 non-null  str
 3   educationno    30161 non-null  int64
 4   maritalstatus  30161 non-null  str
 5   occupation     30161 non-null  str
 6   relationship   30161 non-null  str
 7   race           30161 non-null  str
 8   sex            30161 non-null  str
 9   capitalgain    30161 non-null  int64
 10  capitalloss    30161 non-null  int64
 11  hoursperweek   30161 non-null  int64
 12  native         30161 non-null  str
 13  Salary         30161 non-null  str
dtypes: int64(5), str(9)
memory usage: 3.2 MB

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  str
 2   education      30161 non-null  str
 3   educationno    30161 non-null  int64
 4   maritalstatus  30161 non-null  str
 5   occupation     30161 non-null  str
 6   relationship   30161 non-null  str
 7   race           30161 non-null  str
 8   sex            30161 non-null  str
 9   capitalgain    30161 non-null  int64
 10  capitalloss    30161 non-null  int64
 11  hoursperweek   30161 non-null  int64
 12  native         30161 non-null  str
 13  Salary         30161 non-null  str
dtypes: int64(5), str(9)
memory usage: 3.2 MB

In [7]:
df.describe()

                age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [8]:
df.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='str')

In [9]:
df.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

workclass_encoder = LabelEncoder()
df['workclass'] = workclass_encoder.fit_transform(df['workclass'])

education_encoder = LabelEncoder()
df['education'] = education_encoder.fit_transform(df['education'])

marital_encoder = LabelEncoder()
df['maritalstatus'] =marital_encoder.fit_transform(df['maritalstatus'])

occupation_encoder = LabelEncoder()
df['occupation'] =occupation_encoder.fit_transform(df['occupation'])

relationship_encoder = LabelEncoder()
df['relationship'] =relationship_encoder.fit_transform(df['relationship'])

race_encoder = LabelEncoder()
df['race'] =race_encoder.fit_transform(df['race'])

sex_encoder = LabelEncoder()
df['sex'] =sex_encoder.fit_transform(df['sex'])

native_encoder = LabelEncoder()
df['native'] = native_encoder.fit_transform(df['native'])

salary_encoder = LabelEncoder()
df['Salary'] = salary_encoder.fit_transform(df['Salary'])

In [11]:
df.corr()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
age,1.000000,0.080537,-0.001091,0.043525,-0.276363,-0.005682,-0.246452,0.023380,0.081972,0.080152,0.060278,0.101598,-0.001548,0.241991
workclass,0.080537,1.000000,0.017864,0.037833,-0.034235,0.015572,-0.067414,0.044734,0.074966,0.035349,0.007244,0.050723,0.007598,0.018040
education,-0.001091,0.017864,1.000000,0.345420,-0.040704,-0.038213,-0.012732,0.011139,-0.027831,0.030582,0.014822,0.059892,0.079715,0.079013
educationno,0.043525,0.037833,0.345420,1.000000,-0.063419,0.087717,-0.091935,0.032805,0.006155,0.124416,0.079691,0.152522,0.092625,0.335287
maritalstatus,-0.276363,-0.034235,-0.040704,-0.063419,1.000000,0.022655,0.177955,-0.068641,-0.119774,-0.042414,-0.035385,-0.189004,-0.026057,-0.193504
occupation,-0.005682,0.015572,-0.038213,0.087717,0.022655,1.000000,-0.053727,0.000717,0.062316,0.022162,0.014612,0.018365,-0.003298,0.051577
relationship,-0.246452,-0.067414,-0.012732,-0.091935,0.177955,-0.053727,1.000000,-0.117148,-0.584881,-0.058257,-0.063659,-0.257850,-0.010661,-0.250998
race,0.023380,0.044734,0.011139,0.032805,-0.068641,0.000717,-0.117148,1.000000,0.089207,0.014355,0.023461,0.048533,0.126507,0.071666
sex,0.081972,0.074966,-0.027831,0.006155,-0.119774,0.062316,-0.584881,0.089207,1.000000,0.048809,0.047285,0.231272,0.000063,0.216680
capitalgain,0.080152,0.035349,0.030582,0.124416,-0.042414,0.022162,-0.058257,0.014355,0.048809,1.000000,-0.032218,0.080431,0.008513,0.221195
capitalloss,0.060278,0.007244,0.014822,0.079691,-0.035385,0.014612,-0.063659,0.023461,0.047285,-0.032218,1.000000,0.052454,0.010193,0.150222
hoursperweek,0.101598,0.050723,0.059892,0.152522,-0.189004,0.018365,-0.257850,0.048533,0.231272,0.080431,0.052454,1.000000,0.008429,0.229480
native,-0.001548,0.007598,0.079715,0.092625,-0.026057,-0.003298,-0.010661,0.126507,0.000063,0.008513,0.010193,0.008429,1.000000,0.023515
Salary,0.241991,0.018040,0.079013,0.335287,-0.193504,0.051577,-0.250998,0.071666,0.216680,0.221195,0.150222,0.229480,0.023515,1.000000

In [12]:
from sklearn.preprocessing import LabelEncoder

workclass_encoder = LabelEncoder()
df1['workclass'] = workclass_encoder.fit_transform(df1['workclass'])

education_encoder = LabelEncoder()
df1['education'] = education_encoder.fit_transform(df1['education'])

marital_encoder = LabelEncoder()
df1['maritalstatus'] =marital_encoder.fit_transform(df1['maritalstatus'])

occupation_encoder = LabelEncoder()
df1['occupation'] =occupation_encoder.fit_transform(df1['occupation'])

relationship_encoder = LabelEncoder()
df1['relationship'] =relationship_encoder.fit_transform(df1['relationship'])

race_encoder = LabelEncoder()
df1['race'] =race_encoder.fit_transform(df1['race'])

sex_encoder = LabelEncoder()
df1['sex'] =sex_encoder.fit_transform(df1['sex'])

native_encoder = LabelEncoder()
df1['native'] = native_encoder.fit_transform(df1['native'])

salary_encoder = LabelEncoder()
df1['Salary'] = salary_encoder.fit_transform(df1['Salary'])

In [13]:
x=df.drop('Salary',axis=1)
y=df['Salary']

In [14]:
x_test=df1.drop('Salary',axis=1)
y_test=df1['Salary']

In [15]:
def logistic_regression_model():
    from sklearn.linear_model import LogisticRegressionCV
    model = LogisticRegressionCV()
    model.fit(x,y)
    return model

def naive_bayes_model():
    from sklearn.naive_bayes import GaussianNB
    model = GaussianNB()
    model.fit(x,y)
    return model

def knn_model():
    from sklearn.neighbors import KNeighborsClassifier
    model = KNeighborsClassifier()
    model.fit(x,y)
    return model

def svm_model():
    from sklearn.svm import SVC
    model = SVC()
    model.fit(x,y)
    return model

def decision_tree_model():
    from sklearn.tree import DecisionTreeClassifier
    model = DecisionTreeClassifier()
    model.fit(x,y)
    return model

def random_forest_model():
    from sklearn.ensemble import RandomForestClassifier
    model = RandomForestClassifier()
    model.fit(x,y)
    return model

def adaboost_model():
    from sklearn.ensemble import AdaBoostClassifier
    model = AdaBoostClassifier()
    model.fit(x,y)
    return model

In [16]:
models = [
    {"model_name":"Logistic Regression","model":logistic_regression_model()},
    {"model_name":"Naive Bayes","model":naive_bayes_model()},
    {"model_name":"KNN","model":knn_model()},
    {"model_name":"SVM","model":svm_model()},
    {"model_name":"Decision Tree","model":decision_tree_model()},
    {"model_name":"Random Forest","model":random_forest_model()},
    {"model_name":"ADA Boost","model":adaboost_model()}
]

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [17]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
def evaluate_model(model,model_name,x,y):
    y_pred = model.predict(x)
    
    accuracy = accuracy_score(y,y_pred)
    precision = precision_score(y,y_pred)
    recall = recall_score(y,y_pred)
    f1 = f1_score(y,y_pred)
    
    cm = confusion_matrix(y,y_pred)
    tn,fp,fn,tp = cm.ravel()
    accuracy_cm = (tn+tp)/(tn+tp+fn+fp)

      # return the statistics
    return model_name, accuracy, precision, recall, f1, accuracy_cm

In [18]:
# compare the models by evaluating them
metrics_train = []
for model_info in models:
    # evaluate the model and collect the metrics
    metrics_train.append(evaluate_model(model_info['model'], model_info['model_name'], x, y))
# convert the list of tuples to a data frame
pd.DataFrame(metrics_train, columns=['Algorithm', 'Accuracy', 'Precision', 'Recall', 'F1 Score','CM Accuracy'])

             Algorithm  Accuracy  Precision    Recall  F1 Score  CM Accuracy
0  Logistic Regression  0.812738   0.691595  0.447123  0.543116     0.812738
1          Naive Bayes  0.795332   0.683834  0.330714  0.445821     0.795332
2                  KNN  0.883691   0.790782  0.724427  0.756152     0.883691
3                  SVM  0.796028   0.745474  0.274241  0.400974     0.796028
4        Decision Tree  0.975034   0.982156  0.916356  0.948115     0.975034
5        Random Forest  0.974935   0.961202  0.937134  0.949015     0.974935
6            ADA Boost  0.846557   0.784810  0.528503  0.631646     0.846557

In [19]:
# compare the models by evaluating them
metrics_test = []
for model_info in models:
    # evaluate the model and collect the metrics
    metrics_test.append(evaluate_model(model_info['model'], model_info['model_name'], x_test, y_test))
# convert the list of tuples to a data frame
pd.DataFrame(metrics_test, columns=['Algorithm', 'Accuracy', 'Precision', 'Recall', 'F1 Score','CM Accuracy'])

             Algorithm  Accuracy  Precision    Recall  F1 Score  CM Accuracy
0  Logistic Regression  0.811753   0.677472  0.446216  0.538048     0.811753
1          Naive Bayes  0.794688   0.667956  0.326757  0.438838     0.794688
2                  KNN  0.835525   0.677298  0.631351  0.653518     0.835525
3                  SVM  0.796414   0.733088  0.269459  0.394071     0.796414
4        Decision Tree  0.810491   0.616145  0.606486  0.611278     0.810491
5        Random Forest  0.844422   0.708065  0.624054  0.663410     0.844422
6            ADA Boost  0.846414   0.777289  0.525405  0.626996     0.846414